# Generated by Django 5.2.13 on 2026-04-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdelt_event_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('country_iso', models.CharField(db_index=True, max_length=3)),
                ('event_date', models.DateTimeField(db_index=True)),
                ('headline', models.CharField(max_length=500)),
                ('event_type', models.CharField(choices=[('statement', 'Statement'), ('appeal', 'Appeal'), ('agreement', 'Agreement'), ('consultation', 'Consultation'), ('diplomatic', 'Diplomatic'), ('military', 'Military'), ('incident', 'Incident'), ('protest', 'Protest')], max_length=20)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('goldstein', models.FloatField(default=0.0)),
                ('num_articles', models.IntegerField(default=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=800)),
                ('source', models.CharField(default='GDELT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['country_iso', 'event_date'], name='ingestion_d_country_18fb75_idx'), models.Index(fields=['sentiment', 'event_date'], name='ingestion_d_sentime_d28e40_idx')],
            },
        ),
    ]
