# Generated by Django 5.2.13 on 2026-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticevent',
            name='source_url',
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
