# Generated by Django 5.2.13 on 2026-04-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_diplomaticevent_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomaticevent',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
