[phases.setup]
nixPkgs = ["nodejs_20", "python312"]

[phases.install]
cmds = [
    "python3 -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    "cd frontend && npm install && npx ng build --configuration production && cd ..",
    ". /opt/venv/bin/activate && python3 manage.py collectstatic --noinput"
]
